### ISSUE TITLE
Get conn‘s db name？

### ISSUE THREAD

**Issue by gensuineixin** [Cito/DBUtils#21]
Hello，How can i get the conn object's db name?

**Comment by Cito** [comment]
Depends on the database driver you're using. You need to get the underlying connection first (someting like `_con.con` or `_con._con` depending on whether it's a shared connection), and then get the properties of that connection. Probably you need to parse the dsn to get the database. There's not standard way in DB API 2 to get the database. You're supposed to know it already since you connected to it.

You can also query the current database via an SQL command. In Postgres for instance, you would do that with `SELECT current_database()`.

**Comment by gensuineixin** [comment]
Yes，With "_con._con",I get the db name! Thank you !
