### ISSUE TITLE
mssql failover and segmentation fault

### ISSUE THREAD

**Issue by sevenguin** [Cito/DBUtils#3]
Hi,
    I meet a question, when i use this package to connnect mssql(pymyssql), when the server failover, my program will killed, and just have a message 'Segmentation fault'.
    I use strace to track the error, and get messages like:
   `close(5)                                = 0
--- SIGSEGV {si_signo=SIGSEGV, si_code=SI_KERNEL, si_addr=0} ---
+++ killed by SIGSEGV +++`
   null pointer？

**Comment by Cito** [comment]
Looks like a pymssql issue. Are you using the latest version? Some segfault issues have been fixed there.

**Comment by sevenguin** [comment]
The pymssql is the latest version, and I just use pymssql to connect, when the server failover, it will raise an exception.

**Comment by Cito** [comment]
Generally, DBUtils has been mainly tested with Postgres. But it should work with MS SQL as well since DBUtils is high-level Python code using the DB-API 2 interface. Segfaults usually indicate a problem of the lower level interface like pymssql using C (Cython) extensions - sometimes long-living connections and reuse of connections from pools are not handled properly there.

So please report the issue to the pymssql maintainers. You will need to provide more details, like exact operating system and Python version. Could be a bug that has not yet been discovered or this issue here which looks similar and still exists in the latest version: pymssql/pymssql#406

**Comment by sevenguin** [comment]
Thanks, I understand the relationship between dbutils and pymyssql.
